// Display-only vocabulary. Never applied to API payloads, identifiers or raw evidence.
export const chineseDisplay: Record<string, string> = {
  "LUNA TERMINAL": "交易员工作台",
  "AI Autonomous Trader Console (N10)": "AI 自主交易控制台",
  "Trading Authorization Wizard (N09)": "交易授权向导",
  "No durable plan is available / 暂无可核验的持久化计划。状态：": "暂无可核验的交易计划，状态：",
  "I explicitly grant local authorization for AI to place and manage orders within these exact limits. AI will not ask for per-order confirmation. Expiry or revocation will freeze new risk while preserving protective stop orders.": "我明确授权 AI 在以上范围内自动下单与管理订单，无须逐笔确认。授权到期或撤销后停止新增风险，但保留已有持仓的保护性止损。",
  "(No autonomous cycles recorded in session database)": "（当前账户尚无自主决策记录）",
  "NO REGISTERED ACCOUNT": "未注册账户", "NO ACTIVE SCOPE": "无有效授权",
  "AUTHORIZATION STATUS": "授权状态", "EXPIRY COUNTDOWN": "到期倒计时",
  "PROTECTED POSITIONS": "受保护持仓", "Latest Autonomous Cycle:": "最近自主决策：",
  "Autonomous Engine Status:": "自主交易引擎状态：", "Verdict Action:": "决策动作：",
  "Decision Reason:": "决策依据：", "Rejection Code:": "拒绝原因：",
  "Launch AI Session": "启动 AI 交易", "Pause AI": "暂停 AI 交易", "Resume AI": "恢复 AI 交易",
  "Scope Wizard": "授权向导", "Revoke Scope": "撤销授权", "Trading account": "交易账户",
  "Account:": "账户：", "Session:": "会话：", "(Gen": "（代次", "Scope:": "范围：",
  "Trade Plans / 交易计划": "交易计划", "Trigger / 触发:": "触发条件：",
  "Condition / 条件:": "条件状态：", "Behavior / 行为:": "执行行为：",
  "Evidence / 证据:": "依据：", "News gate / 新闻门槛:": "新闻核验：",
  "Latency:": "耗时：", "Time:": "时间：", "Market Feed:": "行情状态：", "Model:": "模型：",
  "Account ID": "账户编号", "Target Mode": "执行环境", "Decision Path": "决策来源",
  "PAPER (Simulation)": "模拟交易", "TESTNET (Sandbox Venue)": "交易所测试环境",
  "LIVE (Real Capital - Strict Lock)": "真实资金（严格锁定）", "LIVE (LOCKED)": "实盘（已锁定）",
  "AI_LED (Autonomous Bonsai-2-27B Decisions)": "AI 自主决策（Bonsai-2-27B）",
  "STRATEGY_DRIVEN (Quant Rules + Review)": "量化策略驱动（规则与审查）",
  "Allowed Instruments": "允许交易的品种", "Max Risk / Trade": "单笔最大风险",
  "Max Leverage": "最大杠杆", "Validity Duration": "授权有效期",
  "1 Hour": "1 小时", "4 Hours": "4 小时", "12 Hours": "12 小时", "24 Hours": "24 小时",
  "Allow Long Positions": "允许做多", "Allow Short Positions": "允许做空",
  "Grant Authorization": "确认授权", "Authorizing...": "正在授权…",
  "Grant Scope Authorization": "确认范围授权", "Granting...": "正在授权…",
  "A registered account is required before granting authorization.": "请先选择已注册的交易账户，再授予交易权限。",
  "You must explicitly verify local authorization.": "必须由你明确确认本地交易授权。",
  "Network error": "网络请求失败，请检查连接。",
  "Diagnostics": "诊断包", "Exporting...": "正在导出…", "Cancel": "取消", "Stop": "终止", "Active": "有效",
  "3-Factor Engine": "宏观三要素", "Gate.io Swap Ticker": "Gate.io 永续行情",
  "Gate.io Swap": "Gate.io 永续合约", "Exactly-once": "幂等执行",
  "EMA / Squeeze / SMC": "均线趋势 / 波动挤压 / 流动性结构",
  "CoT 推演审单": "AI 决策摘要", "BONSAI · LOCAL MODEL": "Bonsai-2-27B · 本地模型",
  "NOT_CHECKED": "尚未检查", "NOT_RUN": "尚未运行", "UNVERIFIED": "待核验", "UNSCOPED": "未选账户",
  "NO_DURABLE_PLANS": "暂无持久化计划", "NOT_REPORTED": "尚未报告", "LOADED": "已加载",
  "LEGACY_UNCONFIRMED": "历史归属待确认", "STRATEGY_DRIVEN": "策略驱动", "AI_FILTERED": "AI 筛选",
  "AI_LED": "AI 自主决策", "MANUAL": "人工操作", "PAPER": "模拟交易", "TESTNET": "测试环境", "LIVE": "实盘",
  "LOCKED": "已锁定", "ACTIVE": "有效", "HEALTHY": "正常", "IDLE": "空闲", "TERMINATED": "已终止",
  "PARTIALLY_CLOSED": "部分平仓", "PARTIALLY_FILLED": "部分成交", "FILLED": "已成交", "CLOSED": "已平仓",
  "WAITING_TRIGGER": "等待触发", "SUBMITTED": "已提交待成交", "EXECUTED": "已成交", "REJECTED": "已拒绝", "CANCELLED": "已撤销",
  "ENTRY": "开仓", "EXIT": "平仓", "OPEN_LONG": "开多仓", "OPEN_SHORT": "开空仓", "REDUCE_POSITION": "减仓",
  "CLOSE_POSITION": "平仓", "HOLD": "持有", "BUY": "买入", "SELL": "卖出",
  "FORBID_LONG": "禁止做多", "FORBID_SHORT": "禁止做空", "FORBID_ALL": "禁止开仓", "NONE": "无有效限制指令",
  "MARKET_DATA_UNAVAILABLE": "缺少可用行情", "MACRO_UNAVAILABLE": "缺少有效宏观证据",
  "BLOCKED_BY_MACRO_CIRCUIT_BREAKER": "宏观风控已拦截", "NOT_FILLED_PENDING": "尚未成交，等待处理",
  "SCHEDULE_ONLY": "仅有日程", "NOT_FETCHED": "尚未更新", "SCOPED": "已绑定账户",
  "FRESH_MARK": "新鲜行情触发", "MAX_CHASE_BPS": "追价上限", "PERCENT": "百分比",
  "UNKNOWN / 未知": "未知", "UNKNOWN": "未知", "UNAVAILABLE": "不可用", "DEGRADED": "降级运行",
  "recorded": "条记录", "revision": "修订版本", "entry expires": "入场截止", "time exit": "定时退出",
  "partials": "分批止盈", "trailing": "移动止损", "leverage": "杠杆", "reduce": "减仓比例", "qty": "数量", "stop": "止损", "tp": "止盈", "take profit": "止盈", "abandon": "放弃追价",
  "Core CPI": "核心消费者价格指数", "Core PPI": "核心生产者价格指数", "CPI": "消费者价格指数", "PPI": "生产者价格指数",
  "Non-Farm Employment Change": "非农就业人数变化", "Nonfarm Payrolls": "非农就业人数",
  "Unemployment Claims": "初请失业金人数", "Unemployment Rate": "失业率",
  "Federal Funds Rate": "联邦基金利率", "FOMC Statement": "美联储议息声明",
  "FOMC Press Conference": "美联储新闻发布会", "FOMC Meeting Minutes": "美联储会议纪要",
  "Main Refinancing Rate": "主要再融资利率", "Monetary Policy Statement": "货币政策声明",
  "ECB Press Conference": "欧洲央行新闻发布会", "ECB President Lagarde Speaks": "欧洲央行行长拉加德讲话",
  "Prelim UoM Consumer Sentiment": "密歇根大学消费者信心初值", "Prelim UoM Inflation Expectations": "密歇根大学通胀预期初值",
  "SNB Chairman Schlegel Speaks": "瑞士央行行长施莱格尔讲话", "Monetary Policy Report Hearings": "货币政策报告听证会",
  "Retail Sales": "零售销售", "Core Retail Sales": "核心零售销售", "GDP": "国内生产总值",
  "ISM Manufacturing PMI": "供应管理协会制造业采购经理指数", "ISM Services PMI": "供应管理协会服务业采购经理指数",
  "m/m": "环比", "y/y": "同比", "q/q": "季环比",
};

const phrases = Object.entries(chineseDisplay).sort((a, b) => b[0].length - a[0].length);
export function chineseDisplayText(value: string): string {
  if (/^\s*(?:\[|\{)/.test(value) || /^https?:\/\//.test(value.trim())) return value;
  let output = value;
  for (const [source, translated] of phrases) {
    const escaped = source.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    output = output.replace(new RegExp(`(?<![A-Za-z0-9_])${escaped}(?![A-Za-z0-9_])`, "g"), translated);
  }
  return output;
}
