import { useI18n } from "./i18n";

export type StrategyId =
  | "ema_trend"
  | "bollinger_squeeze"
  | "liquidity_sweep"
  | "session_vwap"
  | "opening_range_breakout"
  | "funding_extreme";

export interface StrategyMeta {
  id: StrategyId;
  nameZh: string;
  nameEn: string;
  classificationZh: string;
  classificationEn: string;
  styleZh: string;
  styleEn: string;
  badgeVariant: "bull" | "neutral" | "bear" | "warning" | "gold";
  isRecommended?: boolean;
}

export const STRATEGY_CATALOG: Record<StrategyId, StrategyMeta> = {
  ema_trend: {
    id: "ema_trend",
    nameZh: "EMA 动态通道动能策略",
    nameEn: "EMA Trend Momentum",
    classificationZh: "稳健 · 趋势追踪型",
    classificationEn: "Conservative · Trend Following",
    styleZh: "稳健型",
    styleEn: "Conservative",
    badgeVariant: "bull",
    isRecommended: true,
  },
  session_vwap: {
    id: "session_vwap",
    nameZh: "会话 VWAP 均值回归策略",
    nameEn: "Session VWAP Mean Reversion",
    classificationZh: "稳健 · 价值中枢回归型",
    classificationEn: "Conservative · Mean Reversion",
    styleZh: "稳健型",
    styleEn: "Conservative",
    badgeVariant: "bull",
  },
  bollinger_squeeze: {
    id: "bollinger_squeeze",
    nameZh: "布林带/ATR 挤压突破策略",
    nameEn: "Bollinger Squeeze Breakout",
    classificationZh: "平衡 · 波动蓄势爆发型",
    classificationEn: "Balanced · Volatility Breakout",
    styleZh: "平衡型",
    styleEn: "Balanced",
    badgeVariant: "neutral",
  },
  liquidity_sweep: {
    id: "liquidity_sweep",
    nameZh: "流动性扫荡与订单块反转",
    nameEn: "Liquidity Sweep Reversal",
    classificationZh: "进阶 · 机构猎杀反转型",
    classificationEn: "Advanced · Institutional Reversal",
    styleZh: "进阶型",
    styleEn: "Advanced",
    badgeVariant: "warning",
  },
  opening_range_breakout: {
    id: "opening_range_breakout",
    nameZh: "开盘区间突破策略 (ORB)",
    nameEn: "Opening Range Breakout (ORB)",
    classificationZh: "激进 · 日内放量突破型",
    classificationEn: "Aggressive · Day-trading Momentum",
    styleZh: "激进型",
    styleEn: "Aggressive",
    badgeVariant: "bear",
  },
  funding_extreme: {
    id: "funding_extreme",
    nameZh: "资金费率/OI 极值挤压策略",
    nameEn: "Funding Extreme / OI Squeeze",
    classificationZh: "对冲 · 衍生品多空挤压型",
    classificationEn: "Hedging · Derivatives Squeeze",
    styleZh: "对冲型",
    styleEn: "Hedging",
    badgeVariant: "gold",
  },
};

export function getStrategyOptionLabel(meta: StrategyMeta, zh: boolean): string {
  const prefix = meta.isRecommended ? "⭐ [系统推荐] " : "";
  const tag = zh ? `[${meta.classificationZh}]` : `[${meta.classificationEn}]`;
  const name = zh ? meta.nameZh : meta.nameEn;
  return `${prefix}${tag} ${name}`;
}

const en = {
  timeframe: "Timeframe",
  bars: "bars",
  macroPermission:
    "Allow SIMULATION with unknown macro evidence (default off; active macro blocks still enforced)",
  dashboard: "Trading desk",
  monitor: "Watch & monitor",
  strategies: "Strategy library",
  intel: "News & macro",
  safety: "LOCAL SIMULATION · Real execution and external messaging locked",
  unavailable:
    "Backend unavailable. Saved values cannot be verified. No automatic model call or trade.",
  add: "Add Gate contract",
  symbol: "Symbol (e.g. BTCUSDT)",
  remove: "Remove",
  attach: "Attach strategy",
  enable: "Monitor",
  start: "Start",
  pause: "Pause",
  resume: "Resume",
  stop: "Stop",
  running: "Running",
  paused: "Paused",
  stopped: "Stopped",
  startMonitoring: "Start Monitoring",
  pauseMonitoring: "Pause Monitoring",
  stopMonitoring: "Stop Monitoring",
  startAll: "▶ Start All",
  pauseAll: "⏸ Pause All",
  stopAll: "⏹ Stop All",
  singleStrategyNotice: "Single strategy exclusive per symbol",
  recommendedBadge: "⭐ System Recommended",
  emergency: "Emergency stop",
  worker: "Monitoring worker",
  noWatch:
    "No watched contracts. Add a Gate USDT perpetual; monitoring stays off until you enable a strategy.",
  noDecisions:
    "No strategy proposal yet. The rules below require closed bars; absence of a trigger is not a buy or sell signal.",
  noChart:
    "No stored bars yet. Public read-only hydration fetches data; source failures are shown, never replaced by demo prices.",
  chart: "Price / volume",
  evidence: "Source evidence",
  news: "News · past 48 hours",
  macro: "Scheduled macro releases",
  noNews:
    "No dated news in the last 48 hours. Provider may be unavailable; old and unknown-date stories are excluded.",
  noMacro:
    "Structured macro provider not configured. RSS is news, not a release calendar. Previous / forecast / actual unavailable; simulation entry is blocked by MacroGuard.",
  analyze: "Ask AI explicitly",
  source: "Source",
  time: "As of",
  period: "24h change",
  unknown: "Unavailable / unknown",
  model:
    "Qwen 9B runs only for a new strategy proposal or an explicit consultation. No 4B Smart substitution.",
  decisions: "Decision & execution log",
  positions: "Simulated positions",
  preferences: "System & preferences",
  ledger: "Simulation ledger",
  noPositions:
    "No simulated positions. This is not proof of a successful execution test.",
  details: "Facts, risk & execution details",
  ema_trend: "EMA trend momentum",
  bollinger_squeeze: "Bollinger squeeze breakout",
  liquidity_sweep: "Liquidity sweep reversal",
  session_vwap: "Session VWAP mean reversion",
  opening_range_breakout: "Opening range breakout (ORB)",
  funding_extreme: "Funding extreme / OI squeeze",
  ema_rule:
    "EMA20 cross + rising/falling slope + volume ≥1.3× + RSI(14) guard. Stop beyond EMA50 by 1.2 ATR; targets 2R / 3.5R.",
  squeeze_rule:
    "Prior Bollinger bands inside Keltner; first volume-confirmed breakout. Stop at prior mid-band; targets 2R / 3R.",
  sweep_rule:
    "Sweep prior 4h extreme, reclaim with long wick and closed 5m engulfing. Missing 5m evidence means no trigger.",
  vwap_rule:
    "Anchor session VWAP ±2.0σ std dev bands. RSI overbought/oversold reversal bar entry. Target VWAP; stop 1.5 ATR.",
  orb_rule:
    "First 30m session range extreme breakout + RVol ≥1.3× volume surge. Stop at range midpoint; target 1.5R / 3R.",
  funding_rule:
    "Funding beyond prior 95th percentile and |rate| >0.05%, with OI rising >5%. Missing histories mean no trigger; not risk-free arbitrage.",
  entryPrice: "Entry price",
  planPrice: "Planned Entry",
  currentPrice: "Market Price",
  planRationale: "Trigger & Risk Rationale",
  currentStop: "Stop loss",
  targetTp: "Targets",
  contracts: "Contracts",
  pnl: "Realized PnL",
  protected: "Protected (SL/TP active)",
  unprotected: "Unprotected",
  rawDiagnostics: "Raw diagnostics (JSON)",
  saved: "Saved",
  retry: "Refresh",
  previous: "Previous",
  forecast: "Forecast",
  actual: "Actual",
  macroBarometer: "Macro Policy Barometer (24h)",
  bullishNews: "Bullish Policies",
  bearishNews: "Bearish Policies",
  neutralNews: "Neutral",
  macroStance: "Liquidity Stance",
  filterAll: "All News",
  filterBull: "Bullish Policy",
  filterBear: "Bearish Policy",
  filterMacro: "Macro Shock",
  sentinelPipeline: "Agent Sentinel Monitoring Pipeline",
  sentinelStep1: "Gate.io WebSocket Feed",
  sentinelStep2: "15m/1h Bar Close Lock",
  sentinelStep3: "Multi-Strategy Scan",
  sentinelStep4: "Qwen 3.5 CoT Reasoning",
  sentinelStep5: "Hard Risk & Order Guard",
  countdown: "Release countdown",
  directive: "Macro Directive",
  activeDirective: "Active Macro Circuit Breaker",
  minutes: "min",
  aiAnalysis: "AI Trading Analysis Desk",
  aiAnalysisSub: "Live Gate TestNet Account Truth · Remote Equity Sync · AI Dynamic 5x~100x Leverage · Style DNA Profiling",
  gateLiveDesk: "Gate.io Live Desk & Trades",
  gateLiveSub: "300+ Active Contracts · Real Trade Ledger & Fees · Pre-reserved Quantitative Interface",
  initialCapital: "Baseline Equity",
  currentEquity: "Current Account Equity",
  totalPnl: "Total Realized PnL",
  winRate: "Win Rate",
  profitFactor: "Profit Factor",
  maxDrawdown: "Max Drawdown",
  dynamicLeverage: "AI Dynamic Leverage",
  styleDna: "AI Trader Style DNA",
  strategyMatrix: "6 Strategies Performance Matrix",
  tradeLedger: "AI Trading Decisions Ledger",
  gateConfig: "Gate.io API Credentials",
  gateMarkets: "Gate.io Contracts Universe",
  gateTrades: "Gate.io Real Trade Ledger",
  gateQuantInterface: "Gate.io Live Quantitative Execution Interface",
  gateApiKey: "API Key",
  gateApiSecret: "API Secret",
  testConnection: "Test & Validate",
  saveConfig: "Save Config",
  dryRunSafety: "Dry-Run Safety Sandbox",
  dryRunDesc: "When active, quantitative orders perform full risk validation without actual fund deduction on Gate.io",
  placeOrder: "Submit Pre-reserved Order",
  closeAllPositions: "Emergency Close All Positions",
  searchContracts: "Search Gate contracts (e.g. BTC, ETH, SOL, SUI...)",
  noGateTrades: "No Gate.io trade records found. Configure API Key to fetch real execution and fee ledger.",
} as const;

const zh: Record<keyof typeof en, string> = {
  timeframe: "周期",
  bars: "根 K 线",
  macroPermission:
    "允许宏观证据未知时进行模拟（默认关闭；已有宏观禁止方向仍强制拦截）",
  dashboard: "综合战情室",
  monitor: "自选与盯盘",
  strategies: "量化与策略库",
  intel: "资讯与宏观",
  safety: "本地模拟 · 真实资金执行与外部推送已锁定",
  unavailable: "后端不可用，无法核验已存数据。不会自动调用模型或交易。",
  add: "添加 Gate 合约",
  symbol: "标的（例如 BTCUSDT）",
  remove: "移除",
  attach: "挂载策略",
  enable: "盯盘",
  start: "开始",
  pause: "暂停",
  resume: "恢复",
  stop: "结束",
  running: "运行中",
  paused: "已暂停",
  stopped: "已结束",
  startMonitoring: "开始盯盘",
  pauseMonitoring: "暂停盯盘",
  stopMonitoring: "结束盯盘",
  startAll: "▶ 全部开始",
  pauseAll: "⏸ 全部暂停",
  stopAll: "⏹ 全部结束",
  singleStrategyNotice: "单标的独占单策略 · 严控风险",
  recommendedBadge: "⭐ 系统推荐",
  emergency: "紧急停止",
  worker: "盯盘守护进程",
  noWatch: "暂无自选合约。添加 Gate USDT 永续合约后，须明确开启策略才会盯盘。",
  noDecisions:
    "尚无策略提案。下列规则只使用已收盘 K 线；未触发不代表买入或卖出信号。",
  noChart:
    "尚无已存 K 线。后台仅抓取公开行情；数据源故障会明确显示，不用演示价格代替。",
  chart: "价格与成交量",
  evidence: "来源证据",
  news: "资讯 · 最近 48 小时",
  macro: "重大宏观日历三要素",
  noNews: "最近 48 小时内暂无快讯。",
  noMacro: "尚无可用日历缓存，请点击“更新公开日历”。数据缺失不等于没有宏观风险；依赖宏观证据的交易仍需通过风控核验。",
  analyze: "呼叫 AI 深度分析",
  source: "来源",
  time: "更新时间",
  period: "24h 涨跌",
  unknown: "不可用 / 未知",
  model:
    "Qwen 9B 仅在策略生成新提案或主动发起投研咨询时运行，绝不用 4B 顶替主力思考。",
  decisions: "决策与执行记录",
  positions: "模拟持仓",
  preferences: "系统与设置",
  ledger: "记账与持仓",
  noPositions: "暂无模拟持仓记录。",
  details: "事实上下文、风控与执行明细",
  ema_trend: "EMA 动态通道动能策略",
  bollinger_squeeze: "布林带/ATR 挤压突破策略",
  liquidity_sweep: "流动性扫荡与订单块反转",
  session_vwap: "会话 VWAP 均值回归策略",
  opening_range_breakout: "开盘区间突破策略 (ORB)",
  funding_extreme: "资金费率/OI 极值挤压策略",
  ema_rule:
    "EMA20/50 金叉 + 均线斜率确认 + 放量≥1.3× + RSI(14)防追高。EMA50下方1.2ATR止损，目标2R/3.5R。",
  squeeze_rule:
    "布林带收缩进 Keltner 通道蓄势；首根放量 K 线强势突破外轨追单。布林中轨止损，目标2R/3R。",
  sweep_rule:
    "猎杀前 4h 高低点止损密集区，长影线拒绝并收回，次级别 5m 吞没反转确认。影线极值外0.1ATR止损。",
  vwap_rule:
    "锚定会话 VWAP 累积均价及 ±2.0σ 标准差带，结合 RSI 超买超卖与价格拒绝反包收敛，博弈向价值中枢回归。止损 1.5 ATR。",
  orb_rule:
    "统计会话开盘区间极值，实体收盘突破关键边界并伴随相对成交量 RVol ≥ 1.3× 放量确认，顺势追击单边趋势。中轨止损。",
  funding_rule:
    "资金费率超 95 分位数且绝对值>0.05%，持仓量 (OI) 异动>5%。多空挤压预警反向防守布局。",
  entryPrice: "开仓价",
  planPrice: "计划入场价",
  currentPrice: "参考市价",
  planRationale: "量化触发与风控逻辑",
  currentStop: "硬止损价",
  targetTp: "目标止盈",
  contracts: "持仓张数",
  pnl: "已实现盈亏",
  protected: "🛡️ 硬止盈止损守护中",
  unprotected: "⚠️ 无守护",
  rawDiagnostics: "诊断与原始数据 (JSON)",
  saved: "已保存",
  retry: "刷新",
  previous: "前值",
  forecast: "预期",
  actual: "公布值",
  macroBarometer: "宏观多空政策晴雨表 (24h)",
  bullishNews: "利多政策",
  bearishNews: "利空政策",
  neutralNews: "中性观望",
  macroStance: "宏观流动性基调",
  filterAll: "全部资讯",
  filterBull: "仅看利多",
  filterBear: "仅看利空",
  filterMacro: "重大宏观",
  sentinelPipeline: "AI 盯盘守护引擎工作链路",
  sentinelStep1: "Gate.io WebSocket 行情",
  sentinelStep2: "15m/1h K线整点收盘",
  sentinelStep3: "六大专业量化策略扫描",
  sentinelStep4: "Qwen 3.5 交易员推演",
  sentinelStep5: "确定性硬风控 (≤2%止损)",
  countdown: "距发布倒计时",
  directive: "宏观风控指令",
  activeDirective: "宏观硬熔断生效中",
  minutes: "分钟",
  aiAnalysis: "AI 做单分析看板",
  aiAnalysisSub: "Gate 模拟盘真实资金 · 远端账户事实同步 · AI 动态 5x~100x 智能杠杆 · 交易员风格洞察",
  gateLiveDesk: "Gate.io 实盘与交易记录",
  gateLiveSub: "300+ 活跃合约全量接入 · 实盘成交明细与手续费核对 · 实盘量化接口预留",
  initialCapital: "起算权益（远端）",
  currentEquity: "当前账户权益",
  totalPnl: "累计已实现净盈亏",
  winRate: "综合胜率",
  profitFactor: "盈亏比 (PF)",
  maxDrawdown: "最大回撤率",
  dynamicLeverage: "AI 自主动态杠杆决策",
  styleDna: "AI 交易员风格画像与评级",
  strategyMatrix: "六大专业策略战绩矩阵",
  tradeLedger: "AI 策略决策与交易明细表",
  gateConfig: "Gate.io 实盘 API 接入配置",
  gateMarkets: "Gate.io 全量活跃永续合约池",
  gateTrades: "Gate.io 实盘成交记录与手续费",
  gateQuantInterface: "Gate.io 实盘量化预留接口",
  gateApiKey: "Gate API Key",
  gateApiSecret: "Gate API Secret",
  testConnection: "测试连通性",
  saveConfig: "保存并验证",
  dryRunSafety: "Dry-Run 安全沙盒模式",
  dryRunDesc: "开启后所有量化买卖、止盈止损均进行全链路风控验证，不实际向 Gate.io 发单扣款",
  placeOrder: "预留接口发单测试",
  closeAllPositions: "一键紧急全平",
  searchContracts: "搜索 Gate 合约（输入 BTC, ETH, SOL, SUI, PEPE...）",
  noGateTrades: "暂无 Gate.io 实盘成交记录。在上方配置 API Key 后可自动读取实盘成交与手续费明细。",
};

export function useV2Copy() {
  const { language } = useI18n();
  return language === "zh-CN" ? zh : en;
}
